version: '3.2'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "changeit"
      POSTGRES_DB: "test"

  oracle:
    image: oracle/database:18.4.0-xe-ready
    ports:
      - 1521:1521
      - 5050:5050
    environment:
      ORACLE_SID: "XE"
      ORACLE_PWD: "changeit"
