CREATE TABLE testdata (
    some_smallserial smallserial,
    some_serial serial,
    some_bigserial bigserial,
    some_bit bit(3),
    some_boolean bool,
    some_varchar    varchar(10),
    some_char    char,
    some_text   text,
    some_name name,
    some_int int,
    some_int2 int2,
    some_int4 int4,
    some_int8 int8,
    some_smallint smallint,
    some_bigint bigint,
    some_float4 float4,
    some_float8 float8,
    some_real real,
    some_double double precision,
    some_timestamp timestamp,
    some_timestamptz timestamptz
--  for now enough
);

INSERT INTO testdata (
    some_bit,
    some_boolean,
    some_varchar,
    some_char,
    some_text,
    some_name,
    some_int,
    some_int2,
    some_int4,
    some_int8,
    some_smallint,
    some_bigint,
    some_float4,
    some_float8,
    some_real,
    some_double,
    some_timestamp,
    some_timestamptz
) VALUES (
    B'101',
    true,
    'varchar-10',
    'c',
    text('text'),
    name('name'),
    1,
    10,
    100,
    1000,
    1,
    10000,
    div(2,3),
    div(2,3),
    div(2,3),
    div(2,3),
    current_timestamp,
    current_timestamp);

INSERT INTO testdata DEFAULT VALUES;