name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: "Build"
        run: rustup update --force && cargo build --verbose

      - name: "Run Unit-Tests"
        run: cargo test --lib --verbose

      - name: "Install Oracle Instant-Client (needed for driver)"
        run: |
          curl -s -o /tmp/oracle-client.rpm https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-basiclite-linuxx64.rpm
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 alien libaio1
          sudo alien -i /tmp/oracle-client.rpm

      - name: "Prepare Certificates"
        run: |
          cd docker/certs
          ./generate-ca.sh
          ./generate-signed-cert.sh server
          ./generate-signed-cert.sh client

      - name: "Startup Databases via Docker"
        run: |
          cd docker
          DOCKER_BUILDKIT=1 docker compose up --quiet-pull -d

      - name: "Run Integration-Tests"
        run: sleep 90 && cargo test --test integration --verbose

      - name: "Check Container Logs"
        if: failure()
        run: |
          cd docker
          docker compose logs